package com.tilevision.shared.export

import com.tilevision.shared.domain.ProjectSummary
import com.tilevision.shared.domain.CostLineItem

/**
 * PDF generation interface
 */
expect class PdfGenerator {
    /**
     * Generate PDF from project summary
     */
    suspend fun generatePdf(summary: ProjectSummary): Result<ByteArray>
}

/**
 * HTML template for PDF generation
 */
fun generateHtmlTemplate(summary: ProjectSummary): String {
    return """
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Tile Project Summary</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                margin: 20px;
                color: #333;
            }
            .header {
                text-align: center;
                border-bottom: 2px solid #007bff;
                padding-bottom: 20px;
                margin-bottom: 30px;
            }
            .project-info {
                background-color: #f8f9fa;
                padding: 20px;
                border-radius: 8px;
                margin-bottom: 20px;
            }
            .cost-breakdown {
                background-color: #fff;
                border: 1px solid #dee2e6;
                border-radius: 8px;
                padding: 20px;
                margin-bottom: 20px;
            }
            .line-item {
                display: flex;
                justify-content: space-between;
                padding: 8px 0;
                border-bottom: 1px solid #eee;
            }
            .line-item:last-child {
                border-bottom: none;
            }
            .total {
                font-weight: bold;
                font-size: 1.2em;
                color: #007bff;
                border-top: 2px solid #007bff;
                padding-top: 10px;
                margin-top: 10px;
            }
            .footer {
                text-align: center;
                margin-top: 30px;
                padding-top: 20px;
                border-top: 1px solid #dee2e6;
                color: #6c757d;
                font-size: 0.9em;
            }
            table {
                width: 100%;
                border-collapse: collapse;
            }
            th, td {
                text-align: left;
                padding: 8px;
                border-bottom: 1px solid #ddd;
            }
            th {
                background-color: #f8f9fa;
                font-weight: bold;
            }
        </style>
    </head>
    <body>
        <div class="header">
            <h1>Tile Project Summary</h1>
            <p>Generated on ${formatDate(summary.generatedAt)}</p>
        </div>
        
        <div class="project-info">
            <h2>Project Information</h2>
            <table>
                <tr>
                    <td><strong>Area:</strong></td>
                    <td>${formatArea(summary.projectInfo.areaSqFt)} ft²</td>
                </tr>
                <tr>
                    <td><strong>Tiles:</strong></td>
                    <td>${summary.projectInfo.tileCount} tiles</td>
                </tr>
                <tr>
                    <td><strong>Boxes:</strong></td>
                    <td>${summary.projectInfo.boxCount} boxes</td>
                </tr>
                <tr>
                    <td><strong>Tile Size:</strong></td>
                    <td>${summary.projectInfo.tileSize}</td>
                </tr>
                <tr>
                    <td><strong>Layout:</strong></td>
                    <td>${summary.projectInfo.layoutType}</td>
                </tr>
            </table>
        </div>
        
        <div class="cost-breakdown">
            <h2>Cost Breakdown</h2>
            ${generateCostTable(summary.costBreakdown.lineItems)}
            
            <div class="total">
                <div class="line-item">
                    <span>Subtotal:</span>
                    <span>$${formatPrice(summary.costBreakdown.subtotal)}</span>
                </div>
                <div class="line-item">
                    <span>Tax:</span>
                    <span>$${formatPrice(summary.costBreakdown.taxAmount)}</span>
                </div>
                <div class="line-item">
                    <span><strong>Total:</strong></span>
                    <span><strong>$${formatPrice(summary.costBreakdown.total)}</strong></span>
                </div>
            </div>
        </div>
        
        <div class="footer">
            <p>Generated by TileVision - Professional Tile Planning Software</p>
        </div>
    </body>
    </html>
    """.trimIndent()
}

private fun generateCostTable(lineItems: List<CostLineItem>): String {
    return """
    <table>
        <thead>
            <tr>
                <th>Description</th>
                <th>Quantity</th>
                <th>Unit Price</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            ${lineItems.joinToString("") { item ->
                """
                <tr>
                    <td>${item.description}</td>
                    <td>${item.quantity}</td>
                    <td>$${formatPrice(item.unitPrice)}</td>
                    <td>$${formatPrice(item.total)}</td>
                </tr>
                """.trimIndent()
            }}
        </tbody>
    </table>
    """.trimIndent()
}

private fun formatDate(timestamp: Long): String {
    // Simple date formatting - in a real app you'd use proper date formatting
    return "Generated on ${timestamp}"
}

private fun formatPrice(price: Double): String {
    return formatDouble(price, 2)
}

private fun formatArea(area: Double): String {
    return formatDouble(area, 1)
}

private fun formatDouble(value: Double, decimals: Int): String {
    val multiplier = 10.0 * decimals // Simple approximation
    val rounded = kotlin.math.round(value * multiplier) / multiplier
    return rounded.toString()
}
